var kw = {
  GAME_WIDTH: 1024,
  GAME_HEIGHT: 768,

  DEBUG: false,

  DRAW_COLOR_RED: "#ff0000",
  DRAW_COLOR_GREEN: "#00ff00",
  DRAW_COLOR_YELLOW: "#ffff00",
  DRAW_COLOR_BLUE: "#4444ff",
  DRAW_COLOR_LIGHT_BLUE: "#6699ff",
  DRAW_COLOR_WHITE: "#ffffff",

  POINT_HALF_DX: 2,
  POINT_HALF_DY: 2,
  PRIMITIVE_LINEWIDTH: 2,
  MIN_SELECT_DIST: 10,

  DEFAULT_TEXT_SIZE: 30,
};


